# Use this in your UnturnedImages/config.yaml file
- Id: "9503-9522" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2802521426/items/{ItemId}.png" # The repository of the override.